version: "3.9"
services:
  chromadb:
    build: ./docker/chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/app/chroma_db

  rag_app:
    build: .
    depends_on:
      - chromadb
    volumes:
      - .:/app
    environment:
      - CHROMA_HOST=chromadb
    ports:
      - "5000:5000"

volumes:
  chromadb_data:
